# Generated by Django 5.1 on 2024-09-05 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositEvent',
            fields=[
                ('accountingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accountingevent')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.money')),
            ],
            bases=('accounts.accountingevent',),
        ),
        migrations.CreateModel(
            name='DepositPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.entrytype')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.eventtype')),
                ('service_agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='accounts.serviceagreement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.money')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_from', to='accounts.account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_to', to='accounts.account')),
                ('transaction_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.transactionstatus')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.transactiontype')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transaction.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransferEvent',
            fields=[
                ('accountingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accountingevent')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.money')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_from', to='accounts.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_to', to='accounts.account')),
            ],
            bases=('accounts.accountingevent',),
        ),
        migrations.CreateModel(
            name='TransferPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.entrytype')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.eventtype')),
                ('service_agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='accounts.serviceagreement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalEvent',
            fields=[
                ('accountingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accountingevent')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.money')),
            ],
            bases=('accounts.accountingevent',),
        ),
        migrations.CreateModel(
            name='WithdrawalPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.entrytype')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.eventtype')),
                ('service_agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='accounts.serviceagreement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
