# Generated by Django 5.1 on 2024-08-31 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PostingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accounttype')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accounts', models.ManyToManyField(to='accounts.account')),
                ('service_agreement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='accounts.serviceagreement')),
            ],
        ),
        migrations.CreateModel(
            name='DepositoPR',
            fields=[
                ('postingrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.postingrule')),
            ],
            bases=('accounts.postingrule',),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounts.account')),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.entrytype')),
            ],
        ),
        migrations.AddField(
            model_name='postingrule',
            name='entry_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.entrytype'),
        ),
        migrations.AddField(
            model_name='postingrule',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.eventtype'),
        ),
        migrations.CreateModel(
            name='AccountingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_occurred', models.DateTimeField()),
                ('when_noticed', models.DateTimeField()),
                ('is_processed', models.BooleanField(default=False)),
                ('adjusted_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='accounts.accountingevent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
                ('resulting_entries', models.ManyToManyField(to='accounts.entry')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.currency')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.money'),
        ),
        migrations.AddField(
            model_name='postingrule',
            name='service_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting_rules', to='accounts.serviceagreement'),
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('accountingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accountingevent')),
                ('new_events', models.ManyToManyField(related_name='adjustments_as_new', to='accounts.accountingevent')),
                ('old_events', models.ManyToManyField(related_name='adjustments_as_old', to='accounts.accountingevent')),
            ],
            bases=('accounts.accountingevent',),
        ),
        migrations.CreateModel(
            name='DepositoAE',
            fields=[
                ('accountingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accountingevent')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.money')),
            ],
            bases=('accounts.accountingevent',),
        ),
    ]
