# Generated by Django 5.1 on 2024-08-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceagreement',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
