# Generated by Django 5.1 on 2024-09-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaqueAE',
            fields=[
                ('accountingevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accountingevent')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.money')),
            ],
            bases=('accounts.accountingevent',),
        ),
        migrations.CreateModel(
            name='SaquePR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.entrytype')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.eventtype')),
                ('service_agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_rules', to='accounts.serviceagreement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
