# Generated by Django 5.1 on 2024-09-02 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_saqueae_saquepr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositopr',
            name='service_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='accounts.serviceagreement'),
        ),
        migrations.AlterField(
            model_name='saquepr',
            name='service_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='accounts.serviceagreement'),
        ),
    ]
